# 一.排序

In [1]:
import numpy as np

## 1.间接排序 

In [2]:
arr1 = np.random.randint(2, 15, size=(3,4))
arr1

array([[ 6, 12,  7,  4],
       [ 3, 12,  4,  8],
       [12, 10,  2,  4]])

In [3]:
arr1.argsort() # 排序后,元素从小到大排序后的索引数组

array([[3, 0, 2, 1],
       [0, 2, 3, 1],
       [2, 3, 1, 0]], dtype=int64)

In [4]:
arr1 = np.array([13, 25, 10])
arr2 = np.array([45, 25, 30])
ind = np.lexsort((arr2, arr1)) # 参数用括号包裹 越靠后优先级越高, 向左依次递减
ind

array([2, 0, 1], dtype=int64)

## 2.去重

In [5]:
flowers = np.array(['玫瑰', '牡丹', '月季', '玫瑰', '水仙', '君子兰', '玫瑰', '满天星'])
flowers

array(['玫瑰', '牡丹', '月季', '玫瑰', '水仙', '君子兰', '玫瑰', '满天星'], dtype='<U3')

In [6]:
np.unique(flowers, return_index=True) # 去重函数返回唯一元素索引值

(array(['君子兰', '月季', '水仙', '满天星', '牡丹', '玫瑰'], dtype='<U3'),
 array([5, 2, 4, 7, 1, 0], dtype=int64))

In [7]:
np.unique(flowers, return_counts=True) # 去重函数返回元素出现的次数

(array(['君子兰', '月季', '水仙', '满天星', '牡丹', '玫瑰'], dtype='<U3'),
 array([1, 1, 1, 1, 1, 3], dtype=int64))

## 3.创建重复数组

In [8]:
arr1 = np.arange(3)
arr1

array([0, 1, 2])

In [9]:
np.tile(arr1, 3) # 对数组重复3次

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [10]:
arr2 = np.random.randint(2, 16, size=(2,3))
arr2

array([[15, 10,  6],
       [13,  7,  9]])

In [11]:
np.tile(arr2, 3) # 对数组重复3次

array([[15, 10,  6, 15, 10,  6, 15, 10,  6],
       [13,  7,  9, 13,  7,  9, 13,  7,  9]])

In [12]:
np.repeat(arr1, 3) # 对元素重复3次

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [13]:
np.repeat(arr2, 3) # 对元素重复3次(不指定方向,返回一个一维数组)

array([15, 15, 15, 10, 10, 10,  6,  6,  6, 13, 13, 13,  7,  7,  7,  9,  9,
        9])

In [14]:
np.repeat(arr2, 3, axis=0) # 对元素重复3次(按照行进行重复)

array([[15, 10,  6],
       [15, 10,  6],
       [15, 10,  6],
       [13,  7,  9],
       [13,  7,  9],
       [13,  7,  9]])

In [15]:
np.repeat(arr2, 3, axis=1) # 对元素重复3次(按照列进行重复)

array([[15, 15, 15, 10, 10, 10,  6,  6,  6],
       [13, 13, 13,  7,  7,  7,  9,  9,  9]])

# 二.常用的统计函数

In [16]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.amax(arr1) # 最大值

9

In [18]:
np.amax(arr1, axis=1) # 按照横轴求最大值, 返回一个一维数组

array([3, 6, 9])

In [19]:
np.amax(arr1, axis=0) # 按照纵轴求最大值, 返回一个一维数组

array([7, 8, 9])

In [20]:
np.amin(arr1) # 最小值

1

In [21]:
np.amin(arr1, axis=1) # 按照横轴求最小值, 返回一个一维数组

array([1, 4, 7])

In [22]:
np.amin(arr1, axis=0) # 按照纵轴求最小值, 返回一个一维数组

array([1, 2, 3])

In [23]:
np.ptp(arr1) # 最差值(等于最大值减最小值)

8

## 1.表现数据波动的函数

In [24]:
arr1 = np.arange(1, 10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.mean(arr1) # 求算术平均数

5.0

In [26]:
np.median(arr1) # 求中位数

5.0

In [27]:
np.var(arr1) # 求方差

6.666666666666667

## 2.其他

In [28]:
np.sum(arr1) # 求和

45

In [29]:
np.cumsum(arr1) # 求累加和

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [30]:
np.cumsum(arr1, axis=0) # 求累加和(按纵轴)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [31]:
np.cumsum(arr1, axis=1) # 求累加和(按横轴)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [32]:
np.cumprod(arr1) # 求累加积

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)