# 一.文件读写操作

save, savetxt, load, loadtxt

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 50, size=(5, 5))
arr1

array([[43,  5, 30, 10, 17],
       [ 9, 35, 32, 11,  7],
       [32, 48, 20, 38, 47],
       [38, 12, 19, 39, 48],
       [26, 13,  8,  9, 13]])

In [3]:
np.save('save_arr1', arr1) # 此处的文件名不需要添加扩展名(npy)

In [4]:
arr2 = np.arange(25).reshape(5, 5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
np.savez('savez_arr', arr1=arr1, arr2=arr2) # 保存数组时, 使用'='关键字指定数组名

In [6]:
arr_load1 = np.load('save_arr1.npy')
arr_load1

array([[43,  5, 30, 10, 17],
       [ 9, 35, 32, 11,  7],
       [32, 48, 20, 38, 47],
       [38, 12, 19, 39, 48],
       [26, 13,  8,  9, 13]])

In [7]:
arr_load2 = np.load('savez_arr.npz')
arr_load2

In [8]:
arr_load2.files # files属性查看

['arr1', 'arr2']

In [9]:
arr_load2['arr1']

array([[43,  5, 30, 10, 17],
       [ 9, 35, 32, 11,  7],
       [32, 48, 20, 38, 47],
       [38, 12, 19, 39, 48],
       [26, 13,  8,  9, 13]])

### 保存为文本文件

In [10]:
np.savetxt('savetxt_arr1.txt', arr1) # 此处的文件名需要添加扩展名

### 读取文本文件

In [11]:
np.loadtxt('savetxt_arr1.txt')

array([[43.,  5., 30., 10., 17.],
       [ 9., 35., 32., 11.,  7.],
       [32., 48., 20., 38., 47.],
       [38., 12., 19., 39., 48.],
       [26., 13.,  8.,  9., 13.]])

# 二.排序

In [12]:
arr1 = np.random.randint(2, 15, 10)
arr1

array([4, 2, 6, 4, 7, 9, 5, 8, 6, 4])

In [13]:
arr1.sort() # 此方法修改了原数组,且没有返回值
arr1

array([2, 4, 4, 4, 5, 6, 6, 7, 8, 9])

In [14]:
arr2 = np.random.randint(2, 15, size=(3, 4))
arr2

array([[ 2,  7,  6,  6],
       [11, 11, 14, 13],
       [ 5,  9, 14,  7]])

In [15]:
arr2.sort() # 缺省按行排列 axis=1
arr2

array([[ 2,  6,  6,  7],
       [11, 11, 13, 14],
       [ 5,  7,  9, 14]])

In [16]:
arr2.sort(axis=0) # 按列排序
arr2

array([[ 2,  6,  6,  7],
       [ 5,  7,  9, 14],
       [11, 11, 13, 14]])

numpy的sort方法会生成一个副本, 原数组不发生改变

In [17]:
arr3 = np.random.randint(2, 15, size=(3, 4))
arr3

array([[11,  6, 13, 14],
       [13,  3, 12,  8],
       [ 5,  6, 14,  8]])

In [18]:
np.sort(arr3) # 有返回值

array([[ 6, 11, 13, 14],
       [ 3,  8, 12, 13],
       [ 5,  6,  8, 14]])

In [19]:
arr3.argsort() # 索引数组

array([[1, 0, 2, 3],
       [1, 3, 2, 0],
       [0, 1, 3, 2]], dtype=int64)