# 一.四则运算

In [1]:
import numpy as np

In [2]:
m = np.array([1, 3, 5])
n = np.array([2, 4, 6])

In [3]:
print('加', m+n)
print('减', m-n)
print('乘', m*n)
print('除', m/n)
print('幂运算', m**n)

加 [ 3  7 11]
减 [-1 -1 -1]
乘 [ 2 12 30]
除 [0.5        0.75       0.83333333]
幂运算 [    1    81 15625]


# 二.比较运算

In [4]:
print(m < n)
print(m > n)
print(m != n)
print(np.all(m!=n)) # 逻辑与 判断所有元素是否为真
print(np.any(m!=n)) # 逻辑或 判断是否有元素为真

[ True  True  True]
[False False False]
[ True  True  True]
True
True


# 三.广播机制

In [5]:
arr1 = np.random.randint(2, 12, size=(2, 3))
arr1

array([[ 5,  9,  9],
       [ 3, 10,  4]])

In [6]:
arr2 = np.random.randint(2, 12, size=3)
arr2

array([7, 2, 4])

In [7]:
arr3 = np.random.randint(2, 12, size=4)
arr3

array([11,  4,  9, 11])

In [8]:
print(arr1 + arr2)

[[12 11 13]
 [10 12  8]]


In [9]:
arr1 = np.random.randint(2, 12, size=(4, 3))
arr1

array([[10,  6,  8],
       [ 6,  7,  8],
       [ 8,  9,  9],
       [10,  8, 11]])

In [10]:
arr2 = np.random.randint(2, 12, size=(4, 1))
arr2

array([[ 5],
       [ 9],
       [ 3],
       [11]])

In [11]:
print(arr1 + arr2)

[[15 11 13]
 [15 16 17]
 [11 12 12]
 [21 19 22]]
