#  整数访问

In [16]:
import numpy as np

In [17]:
arr_1d = np.arange(1, 7)
print(arr_1d)
print(arr_1d[2])

[1 2 3 4 5 6]
3


In [18]:
arr_2d = np.arange(1, 7).reshape(2, 3)
print(arr_2d)
print(arr_2d[1])

[[1 2 3]
 [4 5 6]]
[4 5 6]


## 使用索引访问元素

二维数组[行索引, 列索引], 访问二维数组单个元素

In [19]:
print(arr_2d[1, 2])

6


## 使用切片访问数组

### 切片访问一维数组

In [20]:
arr_1d = np.array([10, 20, 30, 40 ,50, 60])
print(arr_1d[1:3])
print(arr_1d[:3])
print(arr_1d[:-1])
print(arr_1d[::2])

[20 30]
[10 20 30]
[10 20 30 40 50]
[10 30 50]


## 切片访问二维数组

In [21]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[:2])
print("---------------")
print(arr_2d[:2, 0:1]) # 访问前两行, 第一列的元素
print("---------------")
print(arr_2d[:2, 0]) # 返回的是一维数组
print("---------------")
print(arr_2d[:2, 0])

[[1 2 3]
 [4 5 6]]
---------------
[[1]
 [4]]
---------------
[1 4]
---------------
[1 4]


In [22]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d[::2, 1::2])

[[ 2  4]
 [10 12]]


### 练习

In [23]:
arr = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [10, 11, 12, 13]])
print(arr)
print("---------------")
print(arr[1, 2:5])
print("---------------")
print(arr[1:, 2:])
print("---------------")
print(arr[[0, 1, 2], [2, 3, 2]])
print("---------------")
print(arr[1:, (0, 3)]) # 索引第二,三行, 第一,四列

[[ 1  3  5  7]
 [ 2  4  6  8]
 [10 11 12 13]]
---------------
[6 8]
---------------
[[ 6  8]
 [12 13]]
---------------
[ 5  8 12]
---------------
[[ 2  8]
 [10 13]]


In [24]:
print(arr[1, :]) # 2 4 6 8
print(arr[:, 2]) # 5, 6, 12
print(arr[:, 1:3]) # 3 ,5 4, 6 11, 12
print(arr[-2:, -2:]) # 6, 8 12, 13
print(arr[::2, ::2]) # 1, 5 10, 12

[2 4 6 8]
[ 5  6 12]
[[ 3  5]
 [ 4  6]
 [11 12]]
[[ 6  8]
 [12 13]]
[[ 1  5]
 [10 12]]


In [25]:
mask = np.array([1, 0, 1], dtype = np.bool)
print(mask)
print(arr[mask, 2]) # 利用布尔索引确定1,3行, 然后第三列元素

[ True False  True]
[ 5 12]


## 使用花式索引访问一维数组

In [26]:
arr_1d = np.arange(1, 10)
print(arr_1d)
print(arr_1d[[2, 5, 8]]) # 以列表作为索引

[1 2 3 4 5 6 7 8 9]
[3 6 9]


## 使用花式索引访问二维数组

In [27]:
arr_2d = np.arange(1, 10).reshape(3, 3)
print(arr_2d)
print("---------------")
print(arr_2d[[0, 2]])
print("---------------")
print(arr_2d[[0, 2], [1, 1]]) # 二维数组[花式索引, 花式索引]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[[1 2 3]
 [7 8 9]]
---------------
[2 8]


## 使用布尔索引访问元素

In [28]:
print(arr_2d > 5)
print("---------------")
print(arr_2d[arr_2d > 5])

[[False False False]
 [False False  True]
 [ True  True  True]]
---------------
[6 7 8 9]


## 变换数组形态

### reshape与resize函数

In [29]:
arr_shape = np.arange(16)
print(arr_shape)
print(arr_shape.reshape(2, 8)) # reshape是生成一个副本, 并不会改变原来数据, 也不能改变元素的总个数

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [31]:
arr_size = np.arange(16)
print(arr_size)
arr_size.resize(4, 4) # resize原地修改原数组
print(arr_size)
arr_size.resize(3, 4)
print(arr_size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
