# 创建数组
## 一 根据现有数据类型创建数组
### 1.创建一维数组

In [1]:
import numpy as np

In [2]:
array_1 = np.array([1, 2, 3])
print(array_1)

[1 2 3]


### 2.创建二维数组

In [3]:
array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


## 二 根据指定数值创建数组
### 1.1 使用zeros()函数创建数组

In [4]:
array_zeros = np.zeros((2,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


### 1.2 指定数据类型

In [5]:
array_zeros = np.zeros((2,3), dtype = bool)
print(array_zeros)

[[False False False]
 [False False False]]


### 2.1 使用ones()函数创建数组

In [6]:
array_ones = np.ones((2,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


### 2.2 指定数据类型

In [7]:
array_ones = np.ones((2,3), dtype = bool)
print(array_ones)

[[ True  True  True]
 [ True  True  True]]


### 3.使用()函数创建数组

In [8]:
array_zeros = np.zeros((2,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


### 4.使用arange()函数创建数组

In [9]:
array_demo = np.arange(2, 12, 2)
print(array_demo)

[ 2  4  6  8 10]


## 三 shape()函数

In [10]:
array_demo2 = np.arange(2, 14, 2)
print(array_demo2)

[ 2  4  6  8 10 12]


In [11]:
array_demo2.shape = 2, 3
print(array_demo2)

[[ 2  4  6]
 [ 8 10 12]]


### 生成3行4列间隔为2的数组

数组的新形状必须与原形状兼容, 满足"新形状的行数 * 新形状的列数 = 元素的总数"

In [12]:
array_demo3 = np.arange(2, 25, 2).reshape(3, 4)
print(array_demo3)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


## 练习:查看数组形状、数据类型与元素个数

In [13]:
arr1 = np.array((1, 3, 5, 7, 9))
arr2 = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
print(arr1.ndim)
print(arr2.ndim)

1
2


In [14]:
# 查看数组形状
print(arr1.shape)  # (5,)表示为1维数组, 共有5个元素
print(arr2.shape)

(5,)
(2, 3)


In [15]:
# 查看数组数据类型
print(arr1.dtype)
print(arr2.dtype)  # <U1表示无符号的8位整型

int32
<U1


In [16]:
#查看数组元素个数
print(arr1.size)
print(arr2.size)

5
6


### 将二维数组改成三行两列

In [17]:
arr2.shape = 3, 2
print(arr2)

[['a' 'b']
 ['c' 'd']
 ['e' 'f']]


### 多种数据类型

In [18]:
arr3 = np.array([1, 'a', 2])
print(arr3)

['1' 'a' '2']


## 四 使用特殊库函数(randam)

In [19]:
# 生成n个0到1之间0(左闭右开)的随机浮点数数组
arr_test = np.random.random(10)
print(arr_test)

[0.27468607 0.93194196 0.05789127 0.53082869 0.24211538 0.58538261
 0.31853031 0.77669726 0.22807446 0.35535905]


#### 转为2行5列

In [20]:
arr_test = arr_test.reshape(2, 5)
print(arr_test)

[[0.27468607 0.93194196 0.05789127 0.53082869 0.24211538]
 [0.58538261 0.31853031 0.77669726 0.22807446 0.35535905]]


#### 转为5行2列

In [21]:
arr_test = arr_test.reshape(5, 2)
print(arr_test)

[[0.27468607 0.93194196]
 [0.05789127 0.53082869]
 [0.24211538 0.58538261]
 [0.31853031 0.77669726]
 [0.22807446 0.35535905]]


### 1.均匀分布

In [22]:
arr_test2 = np.random.rand(2, 5)
print(arr_test2)

[[0.67430556 0.57405201 0.37945584 0.60150776 0.93356707]
 [0.06530566 0.1336245  0.5118725  0.27377954 0.42414611]]


### 2.正态分布

In [23]:
arr_test3 = np.random.randn(2, 5)
print(arr_test3)

[[ 1.86288807 -0.55798705  1.1360355   1.25113007  0.32633903]
 [ 0.20223968  0.38181154 -0.8729328  -0.21405599 -0.2481962 ]]


### 3.生成整型随机数

可以生成给定上下限范围的随机整数

In [24]:
arr_test4 = np.random.randint(2, 5, size=(2,3))
print(arr_test4)

[[3 4 3]
 [2 2 2]]
